-- Agregar APROBADO_GERENCIA al ENUM de estados
ALTER TABLE documentos MODIFY COLUMN estado ENUM(
    'BORRADOR',
    'EN_REVISION_JURIDICA',
    'EN_REVISION_GERENCIAL',
    'APROBADO_JURIDICA',
    'APROBADO_GERENCIA',
    'FIRMADO',
    'DEVUELTO_JURIDICA',
    'DEVUELTO_GERENCIA',
    'PENDIENTE_FINALIZACION',
    'FINALIZADO'
) DEFAULT 'BORRADOR';
